<?xml version="1.0"?>
<package format="2">
  <name>turtle_drawer</name>
  <version>0.1.0</version>
  <description>基于 ROS1 的自主绘图小车:订阅 turtlesim 位姿,发布速度指令,自动绘制图形(正方形、螺旋线)</description>

  <!-- 维护者信息 -->
  <maintainer email="student@example.com">student</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>rospy</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>geometry_msgs</build_depend>
  <build_depend>message_generation</build_depend>

  <exec_depend>rospy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>message_runtime</exec_depend>
  <exec_depend>turtlesim</exec_depend>

</package>